name: actualizar_ine_rapido

on:
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Python
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
      - name: Actualizar
        run: |
          ./ine_rapido.py --upload
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      - name: Commit
        run: |
          git config --global user.name "actions-bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || (git commit -m "Update data" && git push)
